const config = {
  apiBaseUrl: "https://www.anuation.com/itcrm/admin/",
  basepath: "itcrm",
  anuationcomkey: "",
  anuationlabskey: "",
  lastaccountcount: "27",
  crmtype: "crm4",
  name: "IT CRM",
  authKey: "CRM4_SECRET_KEY",
  featureFlags: {
    enableEmailTracking: false,
    enableCallLogging: true,
  },
  headers: [
    "WO",
    "Title",
    "APPLN.NO.",
    "COUNTRY",
    "PRIOTITY DATE",
    "DEADLINE - 30 mth",
    "DEADLINE - 31 mth",
    "APPLICANT NAME",
    "Applicant Status",
    "CONTACT INFO OF",
    "CONTACT PERSON",
    "EMAIL ID",
    "Domain",
    "PH. NO.",
    "Pages",
    "Claim",
    "Priority",
    "Drawings",
    "ISR",
    "REF. NO.",
    "First Email Date",
    "FollowUp date",
    "Next Follow Up",
    "Email Status",
    "Call Status",
    "Comment",
    "Agent name",
    "Agent Email Id",
    "Agent Domain",
    "Agent Phone",
    "Previous Email Status",
    "Company",
    "IN ",
    "CA ",
    "CN ",
    "JP ",
    "AU ",
    "BR ",
    "US ",
    "KR ",
    "EP ",
    "RU ",
    "MX ",
    "MY ",
    "PH ",
    "TH ",
    "ID ",
    "NZ ",
    "ZA ",
    "VN ",
    "SG ",
    "CO ",
    "",
    "Unique/Dupe",
    "Gen/Non Gen",
    "Month",
    "Sent on",
    "Cron Status",
    "Assigned",
    "Timezone",
    "",
    "Agent Unique/Dupe",
    "Agent Gen/Non Gen",
    "Email sent from",
    "Pct App Status",
  ],
  services: {
    patentshelter: {
      accounts: {
        "210401170743442923": [
          { name: "Iris", account: 1 },
          { name: "Sanjana", account: 2 },
          { name: "Palak", account: 3 },
        ],
      },
      username: { "210401170743442923": "Palak" },
      usernames: [{ key: "210401170743442923", name: "Palak" }],
      usernames2: [{ account: "210401170743442923", name: "Palak" }],
    },
  },
  accounts: {
    "210401170743442923": [
      { name: "iris", account: 1 },
      { name: "sanjana", account: 2 },
      { name: "palak", account: 3 },
    ],
  },
  username: { "210401170743442923": "Palak" },
  usernames: [{ key: "210401170743442923", name: "Palak" }],
  usernames2: [{ account: "210401170743442923", name: "Palak" }],
};

export default config;
